spring.application.name=gymflow-api
server.port=8080

# PostgreSQL
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gymflow}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gymflow}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gymflow_secret_2024}
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://ep-flat-bird-am26s1u3-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_PCRzr9UZ1ugS

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# JWT - hardcoded, no env var dependency
jwt.secret=gymflow-jwt-secret-key-2024-very-long-and-secure-minimum-32-bytes
jwt.expiration=86400000

# File upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# ESSL
essl.adms.enabled=true
essl.adms.path=/api/iclock

# Logging
logging.level.com.gymflow=DEBUG
logging.level.org.springframework.boot=INFO

# S3 Storage (set these for cloud mode, leave empty for local file storage)
app.storage.mode=local
app.storage.s3.bucket=gymflow-signage
app.storage.s3.region=ap-south-1
app.storage.s3.access-key=
app.storage.s3.secret-key=
